interface PreliminaryEnvironmentalForm {
  id?: string;
  activity_name: string;
  activity_type: 'TURISTICA' | 'INDUSTRIAL' | 'AGRO_PECUARIA' | 'ENERGETICA' | 'SERVICOS' | 'OUTRA';
  other_activity_type?: string;
  development_stage: 'NOVA' | 'REABILITACAO' | 'EXPANSAO' | 'OUTRO';
  other_development_stage?: string;
  proponents?: string;
  address: string;
  telephone?: string;
  fax?: string;
  mobile_phone?: string;
  email: string;
  activity_location: string;
  activity_city: string;
  activity_locality?: string;
  activity_district?: string;
  activity_province: 'MAPUTO' | 'MAPUTO_CITY' | 'GAZA' | 'INHAMBANE' | 'SOFALA' | 'MANICA' | 'TETE' | 'ZAMBEZIA' | 'NAMPULA' | 'CABO_DELGADO' | 'NIASSA';
  geographic_coordinates?: string;
  insertion_point: 'RURAL' | 'URBANO' | 'PERIURBANO';
  territorial_planning_framework: 'ESPACO_HABITACIONAL' | 'INDUSTRIAL' | 'SERVICOS' | 'OUTRO';
  activity_infrastructure?: string;
  associated_activities?: string;
  construction_operation_technology_description?: string;
  main_complementary_activities?: string;
  labor_type_quantity_origin?: string;
  raw_materials_type_quantity_origin_and_provenance?: string;
  chemicals_used?: string;
  type_origin_water_energy_consumption?: string;
  fuels_lubricants_origin?: string;
  other_resources_needed?: string;
  land_ownership?: string;
  activity_location_alternatives?: string;
  brief_description_on_local_regional_ref_env_situation?: string;
  physical_characteristics_of_activity_site?: 'PLANICIE' | 'PLANALTO' | 'VALE' | 'MONTANHA';
  predominant_ecosystems?: 'FLUVIAL' | 'LACUSTRE' | 'MARINHO' | 'TERRESTRE';
  location_zone?: 'COSTEIRA' | 'INTERIOR' | 'ILHA';
  type_predominant_vegetation?: 'FLORESTA' | 'SAVANA' | 'OUTRO';
  land_use?: 'AGROPECUARIO' | 'HABITACIONAL' | 'INDUSTRIAL' | 'PROTECCAO' | 'OUTRO';
  existing_infrastructure_around_activity_area?: string;
  total_investment_value?: number;
  created_at?: string;
  updated_at?: string;
}